.environment: &default_environment
  APP_NAME: myapp
  STAGE: ${self:provider.stage}
  REGION: ${self:provider.region}
  SERVICE: ${self:service}
  ENTITY_TABLE_NAME: ${self:service}-entities-${self:provider.stage}
  BUS_NAME: ${cf:event-hub-${self:provider.stage}.busName}
  STREAM_ARN: ${cf:event-hub-${self:provider.stage}.stream1Arn}
  ES_DOMAIN_HOST: ${cf:search-bff-${self:provider.stage}.IndexDomainHost}

dev:
  environment:
    <<: *default_environment
    LOG_LEVEL: "DEBUG"
prod:
  environment:
    <<: *default_environment
    LOG_LEVEL: "INFO"
