name: Deploy serverless service

on:
  workflow_dispatch:
    inputs:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  STAGE: prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure SSH Private key for installation repositories
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Python, install dependencies & run tests
        uses: traxporta/serverless-actions/python@master
      - name: Setup Node and install dependencies
        uses: traxporta/serverless-actions/node@master
      - name: Deploy in us-west-2
        run: npx serverless deploy --stage $STAGE --region us-west-2
      - name: Deploy in us-east-1
        run: npx serverless deploy --stage $STAGE --region us-east-1
