.functions: &default_functions
  listener:
    handler: src.entrypoints.listener.handler.handler
    events:
      - stream:
          arn: ${self:provider.environment.STREAM_ARN}

  trigger:
    handler: src.entrypoints.trigger.handler.handler
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt DynamoTableStreamArnGetter.StreamArn
          batchSize: 100
          startingPosition: TRIM_HORIZON

dev:
  functions: *default_functions
prod:
  functions: *default_functions
stg:
  functions: *default_functions
