service: event-lake-s3

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        VersioningConfiguration:
          Status: Enabled

    DeliveryStream:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        DeliveryStreamType: DirectPut
        ExtendedS3DestinationConfiguration:
          BucketARN:
            Fn::GetAtt: [ Bucket, Arn ]
          Prefix: ${self:provider.region}/
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 50
          CompressionFormat: UNCOMPRESSED
          RoleARN:
            Fn::GetAtt: [ DeliveryRole, Arn ]
          CloudWatchLoggingOptions: ${file(includes.yml):CloudWatchLoggingOptions}

    LogGroup: ${file(includes.yml):LogGroup}
    LogStream: ${file(includes.yml):LogStream}

    DeliveryRole: ${file(includes.yml):DeliveryRole}
    EventBridgeRole: ${file(includes.yml):EventBridgeRole}

    EventRule: 
      Type: AWS::Events::Rule
      Properties: 
        EventBusName: ${cf:event-hub-${self:provider.stage}.busName}
        EventPattern: 
          source: 
            - custom
          detail:
            type:
              - anything-but: fault
        State: ENABLED
        Targets: 
          - Id: EventLake
            Arn: 
              Fn::GetAtt: [ DeliveryStream, Arn ]
            RoleArn:
              Fn::GetAtt: [ EventBridgeRole, Arn ]
            InputTransformer:
              InputTemplate: "<aws.events.event>\n" # the EOL delimiter supports parsing in cli

  Outputs:
    BucketName:
      Value:
        Ref: Bucket
    BucketArn:
      Value:
        Fn::GetAtt: [ Bucket, Arn ]
