.environment: &default_environment
  APP_NAME: myapp
  STAGE: ${self:provider.stage}
  REGION: ${self:provider.region}
  SERVICE: ${self:service}
  BUS_NAME: ${cf:event-hub-${self:provider.stage}.busName}
  BUS_ARN: ${cf:event-hub-${self:provider.stage}.busArn}
  STREAM_ARN: ${cf:event-hub-${self:provider.stage}.stream1Arn}
  NAMESPACE: event-fault
  BUCKET_NAME: !Ref Bucket

dev:
  environment:
    <<: *default_environment
    LOG_LEVEL: "DEBUG"
stg:
  environment:
    <<: *default_environment
    LOG_LEVEL: "DEBUG"
prod:
  environment:
    <<: *default_environment
    LOG_LEVEL: "INFO"
